
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "id": "223e4567-e89b-12d3-a456-426614174014",
  "name": "Isabella Walkerss",
  "email": "isabella.walkesr@example.com",
  "address": "789 Willow St, Springfield",
  "dateOfBirth": "1987-10-17"
}